/**
 * Sample charger data for development
 * 示例充电器数据，用于开发和测试
 */

import { Charger, Brand, Protocol, ConnectorType } from './types.js';

export const sampleChargers: Charger[] = [
  {
    id: 'apple-20w-usb-c',
    brand: Brand.APPLE,
    model: 'A2244',
    displayName: 'Apple 20W USB-C Power Adapter',
    power: {
      maxPower: 20,
      configurations: [
        { voltage: 5, current: 3, power: 15 },
        { voltage: 9, current: 2.22, power: 20 },
      ],
    },
    protocols: [Protocol.PD, Protocol.PD_2_0, Protocol.PD_3_0],
    ports: [
      {
        type: ConnectorType.USB_C,
        count: 1,
        maxPower: 20,
        protocols: [Protocol.PD, Protocol.PD_3_0],
      },
    ],
    physicalSpecs: {
      width: 51,
      height: 51,
      depth: 28,
      weight: 58,
      colors: ['白色'],
    },
    description: 'Apple 原装 20W USB-C 电源适配器，支持快速充电，适用于 iPhone、iPad 和 AirPods。',
    features: [
      '支持 PD 快速充电',
      '原装正品，品质保证',
      '紧凑设计，方便携带',
    ],
    releaseYear: 2020,
    isGaN: false,
    hasFoldingPlug: false,
    manufacturedIn: '中国',
    certifications: ['CCC', 'CE', 'FCC'],
    price: {
      msrp: 149,
      current: 149,
      currency: 'CNY',
    },
    officialUrl: 'https://www.apple.com.cn/shop/product/MU872',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },

  {
    id: 'apple-30w-usb-c',
    brand: Brand.APPLE,
    model: 'A1882',
    displayName: 'Apple 30W USB-C Power Adapter',
    power: {
      maxPower: 30,
      configurations: [
        { voltage: 5, current: 3, power: 15 },
        { voltage: 9, current: 3, power: 27 },
        { voltage: 15, current: 2, power: 30 },
        { voltage: 20, current: 1.5, power: 30 },
      ],
    },
    protocols: [Protocol.PD, Protocol.PD_2_0, Protocol.PD_3_0],
    ports: [
      {
        type: ConnectorType.USB_C,
        count: 1,
        maxPower: 30,
        protocols: [Protocol.PD, Protocol.PD_3_0],
      },
    ],
    physicalSpecs: {
      width: 57,
      height: 57,
      depth: 28,
      weight: 73,
      colors: ['白色'],
    },
    description: 'Apple 30W USB-C 电源适配器，专为 MacBook Air 设计，同时兼容 iPhone 和 iPad 快速充电。',
    features: [
      '支持 30W 快速充电',
      '兼容 MacBook Air',
      '多档电压输出',
    ],
    releaseYear: 2018,
    isGaN: false,
    hasFoldingPlug: false,
    manufacturedIn: '中国',
    certifications: ['CCC', 'CE', 'FCC'],
    price: {
      msrp: 199,
      current: 199,
      currency: 'CNY',
    },
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },

  {
    id: 'anker-525-20w',
    brand: Brand.ANKER,
    model: 'A2133',
    displayName: 'Anker Nano 20W PIQ 3.0',
    power: {
      maxPower: 20,
      configurations: [
        { voltage: 5, current: 3, power: 15 },
        { voltage: 9, current: 2.22, power: 20 },
      ],
    },
    protocols: [Protocol.PD, Protocol.PD_3_0, Protocol.PPS, Protocol.QC_3_0],
    ports: [
      {
        type: ConnectorType.USB_C,
        count: 1,
        maxPower: 20,
        protocols: [Protocol.PD, Protocol.PPS],
      },
    ],
    physicalSpecs: {
      width: 38,
      height: 38,
      depth: 41,
      weight: 39,
      colors: ['白色', '紫色', '蓝色'],
    },
    description: 'Anker Nano 系列 20W 充电器，体积比原装更小，支持 iPhone 快速充电，30 分钟可充至 50%。',
    features: [
      '体积小巧，比 Apple 原装小 45%',
      '支持 iPhone 快速充电',
      'AI 智能温控',
    ],
    releaseYear: 2021,
    isGaN: true,
    hasFoldingPlug: false,
    manufacturedIn: '中国',
    certifications: ['CCC', 'CE', 'FCC', 'RoHS'],
    price: {
      msrp: 79,
      current: 79,
      currency: 'CNY',
    },
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },

  {
    id: 'anker-715-65w',
    brand: Brand.ANKER,
    model: 'A2663',
    displayName: 'Anker 715 Charger (Nano II 65W)',
    power: {
      maxPower: 65,
      configurations: [
        { voltage: 5, current: 3, power: 15 },
        { voltage: 9, current: 3, power: 27 },
        { voltage: 15, current: 3, power: 45 },
        { voltage: 20, current: 3.25, power: 65 },
      ],
    },
    protocols: [Protocol.PD, Protocol.PD_3_0, Protocol.PPS, Protocol.QC_3_0],
    ports: [
      {
        type: ConnectorType.USB_C,
        count: 1,
        maxPower: 65,
        protocols: [Protocol.PD, Protocol.PPS],
      },
      {
        type: ConnectorType.USB_A,
        count: 1,
        maxPower: 12,
        protocols: [Protocol.QC_3_0],
      },
    ],
    physicalSpecs: {
      width: 49,
      height: 49,
      depth: 56,
      weight: 109,
      colors: ['白色', '黑色'],
    },
    description: 'Anker 715 65W 充电器，采用 GaN 技术，体积小巧，可同时为两台设备充电，支持 MacBook Pro。',
    features: [
      '65W 大功率，支持笔记本',
      'GaN 技术体积更小',
      '双口同时充电',
      '折叠插脚设计',
    ],
    releaseYear: 2022,
    isGaN: true,
    hasFoldingPlug: true,
    manufacturedIn: '中国',
    certifications: ['CCC', 'CE', 'FCC', 'RoHS'],
    price: {
      msrp: 199,
      current: 179,
      currency: 'CNY',
    },
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },

  {
    id: 'anker-735-100w',
    brand: Brand.ANKER,
    model: 'A2665',
    displayName: 'Anker 735 Charger (Prime 100W)',
    power: {
      maxPower: 100,
      configurations: [
        { voltage: 5, current: 3, power: 15 },
        { voltage: 9, current: 3, power: 27 },
        { voltage: 15, current: 3, power: 45 },
        { voltage: 20, current: 5, power: 100 },
      ],
    },
    protocols: [Protocol.PD, Protocol.PD_3_0, Protocol.PD_3_1, Protocol.PPS, Protocol.QC_4_0],
    ports: [
      {
        type: ConnectorType.USB_C,
        count: 2,
        maxPower: 100,
        protocols: [Protocol.PD, Protocol.PD_3_1],
        isShared: true,
      },
      {
        type: ConnectorType.USB_A,
        count: 1,
        maxPower: 22.5,
        protocols: [Protocol.QC_4_0],
      },
    ],
    physicalSpecs: {
      width: 55,
      height: 55,
      depth: 64,
      weight: 156,
      colors: ['白色', '黑色'],
    },
    description: 'Anker 735 Prime 100W 充电器，支持 PD 3.1 协议，三个充电口，可同时为多台设备充电，支持两台笔记本同时充电。',
    features: [
      '100W 大功率',
      '支持 PD 3.1',
      '三口同时充电',
      '折叠插脚设计',
      '智能功率分配',
    ],
    releaseYear: 2023,
    isGaN: true,
    hasFoldingPlug: true,
    manufacturedIn: '中国',
    certifications: ['CCC', 'CE', 'FCC', 'RoHS', 'ETL'],
    price: {
      msrp: 299,
      current: 269,
      currency: 'CNY',
    },
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },

  {
    id: 'xiaomi-67w-gan',
    brand: Brand.XIAOMI,
    model: 'MDY-13-EU',
    displayName: '小米 67W GaN 充电器',
    power: {
      maxPower: 67,
      configurations: [
        { voltage: 5, current: 3, power: 15 },
        { voltage: 9, current: 3, power: 27 },
        { voltage: 11, current: 6.1, power: 67 },
      ],
    },
    protocols: [Protocol.PD, Protocol.PD_3_0, Protocol.PPS, Protocol.QC_3_0],
    ports: [
      {
        type: ConnectorType.USB_C,
        count: 1,
        maxPower: 67,
        protocols: [Protocol.PD, Protocol.PPS],
      },
      {
        type: ConnectorType.USB_A,
        count: 1,
        maxPower: 18,
        protocols: [Protocol.QC_3_0],
      },
    ],
    physicalSpecs: {
      width: 53,
      height: 53,
      depth: 67,
      weight: 120,
      colors: ['白色'],
    },
    description: '小米 67W GaN 充电器，采用 GaN 技术，体积小巧，支持小米手机 67W 快充，同时兼容其他品牌设备。',
    features: [
      '67W 快速充电',
      'GaN 技术',
      '双口输出',
      '折叠插脚',
      '支持小米 67W 私有协议',
    ],
    releaseYear: 2022,
    isGaN: true,
    hasFoldingPlug: true,
    manufacturedIn: '中国',
    certifications: ['CCC', 'CE', 'FCC'],
    price: {
      msrp: 129,
      current: 109,
      currency: 'CNY',
    },
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },

  {
    id: 'xiaomi-120w-gan',
    brand: Brand.XIAOMI,
    model: 'MDY-12-ED',
    displayName: '小米 120W GaN 充电器',
    power: {
      maxPower: 120,
      configurations: [
        { voltage: 5, current: 3, power: 15 },
        { voltage: 9, current: 3, power: 27 },
        { voltage: 15, current: 3, power: 45 },
        { voltage: 20, current: 6, power: 120 },
      ],
    },
    protocols: [Protocol.PD, Protocol.PD_3_0, Protocol.PPS, Protocol.QC_5],
    ports: [
      {
        type: ConnectorType.USB_C,
        count: 1,
        maxPower: 120,
        protocols: [Protocol.PD, Protocol.PPS],
      },
      {
        type: ConnectorType.USB_A,
        count: 1,
        maxPower: 120,
        protocols: [Protocol.QC_5],
      },
    ],
    physicalSpecs: {
      width: 61,
      height: 61,
      depth: 77,
      weight: 176,
      colors: ['白色'],
    },
    description: '小米 120W GaN 充电器，超大功率输出，支持小米手机 120W 秒充技术，15 分钟充满。',
    features: [
      '120W 超大功率',
      'GaN 技术',
      '支持小米 120W 私有协议',
      '折叠插脚',
      '智能温控保护',
    ],
    releaseYear: 2023,
    isGaN: true,
    hasFoldingPlug: true,
    manufacturedIn: '中国',
    certifications: ['CCC', 'CE', 'FCC'],
    price: {
      msrp: 199,
      current: 179,
      currency: 'CNY',
    },
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },

  {
    id: 'huawei-65w-scp',
    brand: Brand.HUAWEI,
    model: 'HW-200325CP1',
    displayName: '华为 65W SuperCharge 充电器',
    power: {
      maxPower: 65,
      configurations: [
        { voltage: 5, current: 2, power: 10 },
        { voltage: 9, current: 2, power: 18 },
        { voltage: 10, current: 4, power: 40 },
        { voltage: 11, current: 6, power: 66 },
      ],
    },
    protocols: [Protocol.SCP, Protocol.FCP, Protocol.PD, Protocol.PD_3_0, Protocol.PPS, Protocol.QC_2_0],
    ports: [
      {
        type: ConnectorType.USB_C,
        count: 1,
        maxPower: 65,
        protocols: [Protocol.SCP, Protocol.PD, Protocol.PPS],
      },
      {
        type: ConnectorType.USB_A,
        count: 1,
        maxPower: 66,
        protocols: [Protocol.SCP, Protocol.FCP],
      },
    ],
    physicalSpecs: {
      width: 56,
      height: 56,
      depth: 73,
      weight: 138,
      colors: ['白色'],
    },
    description: '华为 65W SuperCharge 充电器，支持华为 SCP 66W 快充，同时兼容 PD 协议，可为笔记本充电。',
    features: [
      '66W 华为 SuperCharge',
      '支持 SCP/FCP 私有协议',
      '兼容 PD 协议',
      '双口输出',
      '智能识别设备',
    ],
    releaseYear: 2022,
    isGaN: true,
    hasFoldingPlug: true,
    manufacturedIn: '中国',
    certifications: ['CCC', 'CE', 'FCC'],
    price: {
      msrp: 159,
      current: 149,
      currency: 'CNY',
    },
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },

  {
    id: 'baseus-65w-gan',
    brand: Brand.BASEUS,
    model: 'BS-C1601',
    displayName: '倍思 65W 2C1A GaN 充电器',
    power: {
      maxPower: 65,
      configurations: [
        { voltage: 5, current: 3, power: 15 },
        { voltage: 9, current: 3, power: 27 },
        { voltage: 12, current: 3, power: 36 },
        { voltage: 15, current: 3, power: 45 },
        { voltage: 20, current: 3.25, power: 65 },
      ],
    },
    protocols: [Protocol.PD, Protocol.PD_3_0, Protocol.PPS, Protocol.QC_4_0, Protocol.QC_3_0, Protocol.AFC, Protocol.FCP],
    ports: [
      {
        type: ConnectorType.USB_C,
        count: 2,
        maxPower: 65,
        protocols: [Protocol.PD, Protocol.PPS],
        isShared: true,
      },
      {
        type: ConnectorType.USB_A,
        count: 1,
        maxPower: 30,
        protocols: [Protocol.QC_3_0, Protocol.AFC, Protocol.FCP],
      },
    ],
    physicalSpecs: {
      width: 67,
      height: 68,
      depth: 31,
      weight: 123,
      colors: ['白色', '黑色', '紫色'],
    },
    description: '倍思 65W GaN 充电器，三口输出，2C1A 配置，支持多协议快充，可同时为三台设备充电。',
    features: [
      '65GaN 大功率',
      '三口同时充电',
      '支持多种快充协议',
      '数码显示功率',
      '折叠插脚',
    ],
    releaseYear: 2023,
    isGaN: true,
    hasFoldingPlug: true,
    manufacturedIn: '中国',
    certifications: ['CCC', 'CE', 'FCC', 'RoHS'],
    price: {
      msrp: 129,
      current: 99,
      currency: 'CNY',
    },
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },

  {
    id: 'ugreen-140w-gan',
    brand: Brand.UGREEN,
    model: 'CD237',
    displayName: '绿联 140W 氮化镓充电器',
    power: {
      maxPower: 140,
      configurations: [
        { voltage: 5, current: 3, power: 15 },
        { voltage: 9, current: 3, power: 27 },
        { voltage: 12, current: 3, power: 36 },
        { voltage: 15, current: 3, power: 45 },
        { voltage: 20, current: 5, power: 100 },
        { voltage: 28, current: 5, power: 140 },
      ],
    },
    protocols: [Protocol.PD, Protocol.PD_3_0, Protocol.PD_3_1, Protocol.PPS, Protocol.QC_4_0, Protocol.QC_3_0],
    ports: [
      {
        type: ConnectorType.USB_C,
        count: 2,
        maxPower: 140,
        protocols: [Protocol.PD, Protocol.PD_3_1],
        isShared: true,
      },
      {
        type: ConnectorType.USB_A,
        count: 1,
        maxPower: 30,
        protocols: [Protocol.QC_3_0],
      },
    ],
    physicalSpecs: {
      width: 73,
      height: 73,
      depth: 80,
      weight: 215,
      colors: ['黑色', '白色'],
    },
    description: '绿联 140W 氮化镓充电器，支持 PD 3.1 协议，28V 输出，可满足 MacBook Pro 16 英寸的充电需求。',
    features: [
      '140W 超大功率',
      '支持 PD 3.1 (28V)',
      '三口同时充电',
      'GaN 技术',
      '折叠插脚',
      '智能功率分配',
    ],
    releaseYear: 2023,
    isGaN: true,
    hasFoldingPlug: true,
    manufacturedIn: '中国',
    certifications: ['CCC', 'CE', 'FCC', 'RoHS', 'ETL'],
    price: {
      msrp: 399,
      current: 349,
      currency: 'CNY',
    },
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
];
